--1
CREATE TABLE TB_COM_CD_HD (
  GRP_CD VARCHAR(10) NOT NULL,
  GRP_CD_NM VARCHAR(50),
  GRP_CD_RMK VARCHAR(300),
  USE_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (GRP_CD)
);

--2
CREATE TABLE TB_COM_CD_DTL (
  GRP_CD VARCHAR(10),
  SUB_CD VARCHAR(4),
  SUB_CD_KR_NM VARCHAR(50),
  SUB_CD_EN_NM VARCHAR(50),
  PANT_GRP_CD VARCHAR(10),
  SUB_CD_RMK VARCHAR(300),
  CD_SRT INT(3) UNSIGNED,
  USE_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (GRP_CD, SUB_CD)
);

--3
CREATE TABLE TB_STNT_INFOR (
  STNT_NO VARCHAR(14),
  STNT_KR_NM VARCHAR(50),
  STNT_EN_NM VARCHAR(50),
  STNT_JUMIN_NO VARCHAR(15),
  PHOTO_FL_NM VARCHAR(100),
  SEX_SEP_CD VARCHAR(10),
  BRTH_DT VARCHAR(8),
  BRTH_NTN VARCHAR(50),
  BRTH_ARA VARCHAR(50),
  HOM_PHON_NO VARCHAR(30),
  KOR_PHON_NO VARCHAR(30),
  HOUS_ADDR VARCHAR(300),
  CELL_NO VARCHAR(30),
  EML_ADDR VARCHAR(100),
  VSA_DUE_DT VARCHAR(8),
  OLD_ID_NO VARCHAR(14),
  LIBRY_NO VARCHAR(30),
  ENTR_DT VARCHAR(8),
  GRDTN_DT VARCHAR(8),
  LIVTGR_FLG VARCHAR(1),
  LERN_REF_NO VARCHAR(30),
  ENRLL_FLG VARCHAR(1),
  TECH_NO VARCHAR(14),
  DEL_FLG VARCHAR(1),
  STNT_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (STNT_NO)
);

--4
CREATE TABLE TB_TECH_INFOR (
  TECH_NO VARCHAR(14) NOT NULL,
  TECH_KR_NM VARCHAR(50),
  TECH_EN_NM VARCHAR(50),
  PWD_NO VARCHAR(30),
  CLSS_TP_CD VARCHAR(10),
  WRK_BGN_DT VARCHAR(8),
  WRK_FISH_DT VARCHAR(8),
  BRTH_DT VARCHAR(8),
  HOM_PHON_NO VARCHAR(30),
  CELL_NO VARCHAR(30),
  TECH_JUMIN_NO VARCHAR(15),
  SEX_SEP_CD VARCHAR(10),
  WRK_FLG VARCHAR(1),
  BRTH_NTN VARCHAR(50),
  BRTH_ARA VARCHAR(50),
  VSA_DUE_DT VARCHAR(8),
  FIN_SCH_HIST_CD VARCHAR(10),
  CEER_NMYER INT(5) UNSIGNED,
  EML_ADDR VARCHAR(100),
  HOUS_ADDR VARCHAR(300),
  PHOTO_FL_NM VARCHAR(100),
  DEPT_CD VARCHAR(10),
  BIZ_CHRG_CD VARCHAR(10),
  CELL_SRV_TP_CD VARCHAR(10),
  INET_PHON_NO VARCHAR(30),
  LIBRY_NO VARCHAR(30),
  TIN_NO VARCHAR(30),
  SSS_NO VARCHAR(30),
  EMPLY_TP_CD VARCHAR(10),
  WRK_PST_CD VARCHAR(10),
  AUTH_GRP_CD VARCHAR(10),
  TECH_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (TECH_NO)
);

--5
CREATE TABLE TB_TECH_RCD_HIS (
  TECH_NO VARCHAR(14) NOT NULL,
  SCH_HIST_SEQ INT(5) UNSIGNED NOT NULL,
  GRDTN_YER VARCHAR(4),
  SCH_HIST_SEP_CD VARCHAR(10),
  MJR VARCHAR(50),
  SCH_NM VARCHAR(100),
  TECH_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT  DATE,
  MOD_ID  VARCHAR(15),
  MOD_DT  DATE,
  PRIMARY KEY (TECH_NO, SCH_HIST_SEQ)
);

--6
CREATE TABLE TB_TECH_LICEN_MGT (
  TECH_NO VARCHAR(14) NOT NULL,
  CERT_SEP_SEQ INT(5) UNSIGNED NOT NULL,
  CERT_NO VARCHAR(30),
  CERT_NM VARCHAR(50),
  OWNS_DT VARCHAR(8),
  PUBL VARCHAR(100),
  LICEN_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (TECH_NO, CERT_SEP_SEQ)
);

--7
CREATE TABLE TB_STNT_RCD_HIS (
  STNT_NO VARCHAR(14)
  ,SCH_RCRD_SEQ INT(5) UNSIGNED
  ,APPLN_DT VARCHAR(8)
  ,SCH_SEP_CD VARCHAR(10)
  ,APPLN_SEP_CD VARCHAR(10)
  ,SCH_NM VARCHAR(50)
  ,MHA_FLG VARCHAR(1)
  ,STNT_RMK VARCHAR(1000)
  ,REGT_ID VARCHAR(15)
  ,REG_DT DATE
  ,MOD_ID VARCHAR(15)
  ,MOD_DT DATE
  ,PRIMARY KEY (STNT_NO, SCH_RCRD_SEQ)
);

--8
CREATE TABLE TB_STNT_FMLY_INFOR (
  STNT_NO VARCHAR(14),
  FMLY_SEQ INT(5) UNSIGNED,
  FMLY_KR_NM VARCHAR(30),
  FMLY_EN_NM VARCHAR(30),
  FMLY_RELT_CD VARCHAR(10),
  BRTH_DT VARCHAR(8),
  JOB_CD VARCHAR(10),
  MHA_TECH_FLG VARCHAR(1),
  CELL_NO VARCHAR(30),
  EML_ADDR VARCHAR(100),
  FMLY_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (STNT_NO, FMLY_SEQ)
);

--9
CREATE TABLE TB_GRD_CLS_ASIGN (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  YER_CD VARCHAR(10),
  GRD_CD VARCHAR(10),
  CLS_CD VARCHAR(10),
  CLSS_TP_CD VARCHAR(10),
  TECH_NO VARCHAR(14),
  TECH_NO_2 VARCHAR(14),
  TECH_NO_3 VARCHAR(14),
  PRCSS_CD VARCHAR(10),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO)
);

--10
CREATE TABLE TB_SJT_ASIGN (
  YER_GRD_SJT_NO VARCHAR(16) NOT NULL,
  YER_CD VARCHAR(10),
  GRD_CD VARCHAR(10),
  TRM_CD VARCHAR(10),
  TOP_SJT_CD VARCHAR(10),
  SJT_CD VARCHAR(10),
  SUB_SJT_CD VARCHAR(10),
  TECH_NO VARCHAR(14),
  CURR_ITRDC VARCHAR(2000),
  CURR_TRGT VARCHAR(2000),
  TXTBK_NM VARCHAR(2000),
  CNF_FLG VARCHAR(1),
  MON_FLG VARCHAR(1),
  TUES_FLG VARCHAR(1),
  WED_FLG VARCHAR(1),
  THUR_FLG VARCHAR(1),
  FRI_FLG VARCHAR(1),
  SAT_FLG VARCHAR(1),
  SUN_FLG VARCHAR(1),
  MON_PERD_CNT VARCHAR(15),
  TUES_PERD_CNT VARCHAR(15),
  WED_PERD_CNT VARCHAR(15),
  THUR_PERD_CNT VARCHAR(15),
  FRI_PERD_CNT VARCHAR(15),
  SAT_PERD_CNT VARCHAR(15),
  SUN_PERD_CNT VARCHAR(15),
  CMPT_UNT_HOUR INT(3) UNSIGNED,
  TOT_LSSN_HOUR INT(3) UNSIGNED,
  GRDE_INCLN_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_SJT_NO)
);

--11
CREATE TABLE TB_STNT_CLS_ASIGN (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  YER_CD VARCHAR(10),
  GRD_CD VARCHAR(10),
  CLS_CD VARCHAR(10),
  FRST_CLS_DAY INT(5) UNSIGNED,
  SCND_CLS_DAY INT(5) UNSIGNED,
  FRST_RMK VARCHAR(1000),
  SCND_RMK VARCHAR(1000),
  FRST_OPNN VARCHAR(2000),
  SCND_OPNN VARCHAR(2000),
  FRST_OPNN_FNL VARCHAR(2000),
  SCND_OPNN_FNL VARCHAR(2000),
  ASSRT_OPNN VARCHAR(2000),
  ASSRT_OPNN_SCNO VARCHAR(2000),
  ABLT_SKLL VARCHAR(1000),
  STNT_VISN VARCHAR(1000),
  PRNT_VISN VARCHAR(1000),
  TECH_OPNN VARCHAR(1000),
  RAT_SEP_CD VARCHAR(10),
  STNT_PRIO_NO INT(5) UNSIGNED,
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO)
);

--12
CREATE TABLE TB_SJT_APPR_STND (
  YER_GRD_SJT_NO VARCHAR(16) NOT NULL,
  MEUR_CD VARCHAR(10) NOT NULL,
  DIST_MRK DECIMAL(7,2) UNSIGNED,
  APPR_RMK VARCHAR(1000),
  CNF_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_SJT_NO, MEUR_CD)
);

--13
CREATE TABLE TB_STNT_RECORD_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  YER_GRD_SJT_NO VARCHAR(16) NOT NULL,
  MEUR_CD VARCHAR(10) NOT NULL,
  MID_OWNS_SCOR DECIMAL(7,2) UNSIGNED,
  LST_OWNS_SCOR DECIMAL(7,2) UNSIGNED,
  AWARD_RMK VARCHAR(1000),
  CNF_FLG VARCHAR(1),
  CNF_FLG_FNL VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, YER_GRD_SJT_NO, MEUR_CD)
);

--14
CREATE TABLE TB_STNT_ANCE_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  ANCE_SEQ INT(5) UNSIGNED NOT NULL,
  ANCE_DT VARCHAR(8),
  ANCE_FRT_CLS_CD VARCHAR(10),
  ANCE_SND_CLS_CD VARCHAR(10),
  RSN_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, ANCE_SEQ)
);

--15
CREATE TABLE TB_STNT_AWARDS_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  AWRD_SEQ INT(5) UNSIGNED NOT NULL,
  AWRD_DT VARCHAR(8),
  AWRD_NM VARCHAR(100),
  WNNR_STMT VARCHAR(100),
  WNNR_ORG_NM VARCHAR(100),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, AWRD_SEQ)
);

--16
CREATE TABLE TB_STNT_CERT_QUAL_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  CERT_SEQ INT(5) UNSIGNED NOT NULL,
  CERT_NO VARCHAR(30),
  CERT_NM VARCHAR(100),
  OWNS_DT VARCHAR(8),
  CERT_PUBL VARCHAR(100),
  CERT_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, CERT_SEQ)
);

--17
CREATE TABLE TB_SPEC_ACT_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  SPEC_ACT_SEQ INT(5) UNSIGNED NOT NULL,
  BGN_DT VARCHAR(8),
  FISH_DT VARCHAR(8),
  SPEC_ACT_SEP_CD VARCHAR(10),
  ACT_NM VARCHAR(100),
  ACT_HOUR INT(5) UNSIGNED,
  ACT_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, SPEC_ACT_SEQ)
);

--18
CREATE TABLE TB_VOLNT_WRK_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  SRVC_ACT_SEQ INT(5) UNSIGNED NOT NULL,
  SRVC_DT VARCHAR(8),
  SRVC_HOUR INT(5) UNSIGNED,
  SRVC_ARA_NM VARCHAR(100),
  SRVC_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, SRVC_ACT_SEQ)
);

--19
CREATE TABLE TB_HEALTH_STS_MGT (
  YER_GRD_NO VARCHAR(12) NOT NULL,
  STNT_NO VARCHAR(14) NOT NULL,
  HLTH_STS_SEQ INT(5) UNSIGNED NOT NULL,
  HLTH_TALL FLOAT(5,2),
  HLTH_WGT FLOAT(5,2),
  HLTH_STS_CD VARCHAR(10),
  HLTH_RMK VARCHAR(1000),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (YER_GRD_NO, STNT_NO, HLTH_STS_SEQ)
);

--20
CREATE TABLE TB_SYS_PGM_MGT (
  PGM_ID VARCHAR(10) NOT NULL,
  PGM_EN_NM VARCHAR(100),
  PGM_KR_NM VARCHAR(100),
  FILE_LEV VARCHAR(2),
  FILE_PASS VARCHAR(20),
  FILE_NM VARCHAR(10),
  USE_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (PGM_ID)
);

--21
CREATE TABLE TB_SYS_AUTH_MGT (
  AUTH_GRP_CD VARCHAR(10) NOT NULL,
  PGM_ID VARCHAR(10) NOT NULL,
  DATA_USE_FLG VARCHAR(1),
  NEW_USE_FLG VARCHAR(1),
  SER_USE_FLG VARCHAR(1),
  SAV_USE_FLG VARCHAR(1),
  DEL_USE_FLG VARCHAR(1),
  PRT_USE_FLG VARCHAR(1),
  ASGN_USE_FLG VARCHAR(1),
  CFM_USE_FLG VARCHAR(1),
  ETC1_USE_FLG VARCHAR(1),
  ETC2_USE_FLG VARCHAR(1),
  ETC3_USE_FLG VARCHAR(1),
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (AUTH_GRP_CD, PGM_ID)
);

--22
CREATE TABLE TB_DOC_TYPE_MGT (
  ISSUE_YER VARCHAR(4) NOT NULL,
  A_DOC_SEQ INT(7) UNSIGNED,
  C_DOC_SEQ INT(7) UNSIGNED,
  E_DOC_SEQ INT(7) UNSIGNED,
  G_DOC_SEQ INT(7) UNSIGNED,
  M_DOC_SEQ INT(7) UNSIGNED,
  T_DOC_SEQ INT(7) UNSIGNED,
  R_DOC_SEQ INT(7) UNSIGNED,
  REGT_ID VARCHAR(15),
  REG_DT DATE,
  MOD_ID VARCHAR(15),
  MOD_DT DATE,
  PRIMARY KEY (ISSUE_YER)
);
